//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLength.ConverterServiceSoap")]
    public interface ConverterServiceSoap {
        
        // CODEGEN: Generating message contract since element name from from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculateLength", ReplyAction="*")]
        UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponse calculateLength(UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculateLength", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponse> calculateLengthAsync(UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calculateLengthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calculateLength", Namespace="http://tempuri.org/", Order=0)]
        public UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequestBody Body;
        
        public calculateLengthRequest() {
        }
        
        public calculateLengthRequest(UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class calculateLengthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        public calculateLengthRequestBody() {
        }
        
        public calculateLengthRequestBody(double value, string from, string to) {
            this.value = value;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calculateLengthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calculateLengthResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponseBody Body;
        
        public calculateLengthResponse() {
        }
        
        public calculateLengthResponse(UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class calculateLengthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double calculateLengthResult;
        
        public calculateLengthResponseBody() {
        }
        
        public calculateLengthResponseBody(double calculateLengthResult) {
            this.calculateLengthResult = calculateLengthResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConverterServiceSoapChannel : UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterServiceSoapClient : System.ServiceModel.ClientBase<UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap>, UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap {
        
        public ConverterServiceSoapClient() {
        }
        
        public ConverterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponse UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap.calculateLength(UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest request) {
            return base.Channel.calculateLength(request);
        }
        
        public double calculateLength(double value, string from, string to) {
            UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest inValue = new UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest();
            inValue.Body = new UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequestBody();
            inValue.Body.value = value;
            inValue.Body.from = from;
            inValue.Body.to = to;
            UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponse retVal = ((UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap)(this)).calculateLength(inValue);
            return retVal.Body.calculateLengthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponse> UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap.calculateLengthAsync(UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest request) {
            return base.Channel.calculateLengthAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthResponse> calculateLengthAsync(double value, string from, string to) {
            UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest inValue = new UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequest();
            inValue.Body = new UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.calculateLengthRequestBody();
            inValue.Body.value = value;
            inValue.Body.from = from;
            inValue.Body.to = to;
            return ((UnitesWebConverterGroup_P14_1205_11181_2.ServiceReferenceLength.ConverterServiceSoap)(this)).calculateLengthAsync(inValue);
        }
    }
}
